// type
export const COURSES_REQUEST = "COURSES_REQUEST";
export const COURSES_SUCCESS = "COURSES_SUCCESS";
export const COURSES_FAILURE = "COURSES_FAILURE";

export const THEMES_REQUEST = "THEMES_REQUEST";
export const THEMES_SUCCESS = "THEMES_SUCCESS";
export const THEMES_FAILURE = "THEMES_FAILURE";

export const THEORY_REQUEST = "THEORY_REQUEST";
export const THEORY_SUCCESS = "THEORY_SUCCESS";
export const THEORY_FAILURE = "THEORY_FAILURE";

export const PROBLEM_REQUEST = "PROBLEM_REQUEST";
export const PROBLEM_SUCCESS = "PROBLEM_SUCCESS";
export const PROBLEM_FAILURE = "PROBLEM_FAILURE";

export const URL_REQUEST = "URL_REQUEST";
export const URL_SUCCESS = "URL_SUCCESS";
export const URL_FAILURE = "URL_FAILURE";